bookbalance/djangoProject/djangoProject/urls.py
from django.urls import path, include
from example import views
from example.views import index

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('example/',include('example.urls')),
    path('', index, name='index'),
]

bookbalance/djangoProject/example/urls.py
from example import views
from example.views import logout, register, login_view, index, mainpage, \
visualization, chatbox, support, support0, account
from django.urls import path, re_path

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/',register,name='register'),
    path('logout/', logout, name='logout'),
    path('index/',index, name='index'),
    path('mainpage/', mainpage, name='mainpage'),
    path('mainpage/<str:username>/', views.mainpage, name='mainpage_with_username'),
    path('visualization/', visualization, name='visualization'),
    path('chatbox/', chatbox, name='chatbox'),
    path('support/', support, name='support'),
    path('support0/', support0, name='support0'),
    path('create/', views.record_create, name='record_create'),
    path('create/<str:username>/', views.record_create, name='record_create_with_username'),
    path('setbudget/', views.set_budget, name='set_budget'),
    path('report/', views.report_add, name='report'),
    path('search/', views.search, name='search'),
    path('search/<str:username>/', views.search, name='search_with_username'),
    path('chatbox/', views.chatbox, name='chatbox'),

    # Retrieve record list
    path('', views.record_list, name='record_list'),
    path('<str:username>/', views.record_list, name='record_list_with_username'),

    path('visualization/retrieve_current_month_income_expense/', views.retrieve_current_month_income_expense, name='retrieve_current_month_income_expense'),
    path('visualization/retrieve_current_year_income_expense/', views.retrieve_current_year_income_expense, name='retrieve_current_year_income_expense'),
    path('visualization/retrieve_year_has_data/', views.retrieve_year_has_data, name='retrieve_year_has_data'),
    path('visualization/retrieve_month_has_data/', views.retrieve_month_has_data, name='retrieve_month_has_data'),

    # Retrieve single record object
    re_path(r'^(?P<pk>\d+)/(?P<username>[\w.@+-]+)/$', views.record_detail, name='record_detail'),

    # Update a record
    # re_path(r'^(?P<pk>\d+)/update/$', views.record_update, name='record_update'),
    re_path(r'^(?P<pk>\d+)/update/(?P<username>[\w.@+-]+)/$', views.record_update, name='record_update'),


    # Delete a record
    # re_path(r'^(?P<pk>\d+)/delete/$', views.record_delete, name='record_delete'),
    re_path(r'^(?P<pk>\d+)/delete/(?P<username>[\w.@+-]+)/$', views.record_delete, name='record_delete'),

    # account setting
    path('account/<str:username>/', account, name='account'),
]

bookbalance/djangoProject/example/models.py
from django.db import models
from django.core.validators import MinValueValidator
# Create your models here.

class User(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    class Meta():
        app_label = 'example'
        db_table = 'User'


class Catalog(models.IntegerChoices):
    Grocery = 0, 'Grocery'
    Entertainment = 1, 'Entertainment'
    Transportation = 2, 'Transportation'
    Housing = 3, 'Housing'
    Medical = 4, 'Medical'
    Education = 5, 'Education'
    Investment = 6, 'Investment'
    Other = 7, 'Other'

    def __str__(self):
        return self.name


class Record_Type(models.IntegerChoices):
    In = 0, 'In'
    Out = 1, 'Out'
class Record(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    Date = models.DateField()
    Category = models.IntegerField(choices=Catalog.choices)
    description = models.TextField()
    type = models.IntegerField(choices=Record_Type.choices)
    Amount = models.DecimalField(max_digits=10, decimal_places=2,  validators=[MinValueValidator(0.00)])

    class Meta():
        app_label = 'example'
        db_table = 'Record'

class Fund(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    Budget = models.DecimalField(max_digits=10, decimal_places=2)
    Rest = models.DecimalField(max_digits=10, decimal_places=2)
    class Meta():
        app_label = 'example'
        db_table = 'Fund'

class Report(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    report_detail = models.CharField(max_length=255)
    class Meta():
        app_label = 'example'
        db_table = 'Report'

bookbalance/djangoProject/example/views.py
from django.contrib.auth.hashers import make_password
from django.shortcuts import HttpResponse
from django.contrib.auth.models import User as AuthUser
from django.db.models import Sum
from decimal import Decimal
from .models import Record_Type, Report, Catalog
from django.db.models import Q
from django.contrib.auth.hashers import make_password, check_password
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.urls import reverse
from django import forms
from django.http import HttpResponse, JsonResponse

from django.contrib.auth import logout as auth_logout

from . import models
from .models import Fund
from .models import User  # 确保从正确的地方导入你的自定义User模型
from .models import Record
from .forms import RecordForm
import datetime, calendar


from django.db.models.functions import ExtractMonth, ExtractYear

# from .utils import login_required


from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm


''' Login Page '''


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)  # Use get method instead of filter method
        except User.DoesNotExist:
            user = None
        if user and check_password(password, user.password):
            if 'remember' in request.POST:
                response = redirect('mainpage_with_username', username=username)
                response.set_cookie('username', username, max_age=30 * 24 * 60 * 60)
            else:
                request.session['username'] = username
                return redirect('mainpage_with_username', username=username)
            request.session['username'] = username
            return response
        else:
            # Login failed, error message returned
            messages.error(request, 'Incorrect password or username. Please try again.')
            return render(request, 'system/log_in.html')
    else:
        username = request.COOKIES.get('username')
        if username:
            user = User.objects.filter(username=username)
            if user:
                return redirect('mainpage_with_username', username=username)
    return render(request, 'system/log_in.html', {'username': username})


def register(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        repassword = request.POST['repassword']
        if password == repassword:
            if User.objects.filter(username=username).exists():
                messages.error(request, 'Username already exists.')
                return render(request, 'system/register.html')
            else:
                user_data = User()
                user_data.username = username
                user_data.email = email
                user_data.password = make_password(password)
                print(user_data.password)
                user_data.save()
                return redirect('login')
    return render(request, 'system/register.html')


def logout(request):
    auth_logout(request)
    response = redirect('index')
    response.delete_cookie('username')
    response.delete_cookie('password')
    return response


def index(request):
    context = {
        'status': '未登录状态'
    }
    return render(request, 'system/index.html', context)


def mainpage(request, username):
    print("mainpage test username: ", username)
    return render(request, 'system/mainpage.html', {'username': username})


def visualization(request):
    username = request.session.get('username')
    print("visualization session username: ", username)
    return render(request, 'system/visualization.html', {"username": username})


def chatbox(request):
    return render(request, 'system/chatbox.html')


def support(request):
    username = request.session.get("username")
    if username is not None:
        return render(request, 'system/support.html', {'username':username, })
    else:
        return render(request, 'system/support.html')


def support0(request):
    return render(request, 'system/support0.html')



def account(request, username):
    if User.objects.filter(username=username).exists():
        user = User.objects.get(username=username)
    else:
        user = None

    if request.method == 'POST':
        form = PasswordChangeForm(user, request.POST)
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        repassword = request.POST['repassword']
        if new_password == repassword:
            if check_password(old_password, user.password):
                user.password = make_password(new_password)
                user.save()
                error_message=messages.success(request, 'Your password was successfully updated!')
                return redirect(reverse('account', kwargs={'username': user.username}))
            else:
                print("error: Incorrect old password. Please try again.")
                error_message=messages.error(request, 'Incorrect old password. Please try again.')

        else:

            error_message=messages.error(request, 'New password not equal to repeat password.')
            print("error: new password not equal to repeat password.")

    else:
        form = PasswordChangeForm(user)

    return render(request, 'system/account.html', {'form': form, 'username': username, 'user': user})


''' Record CRUD '''


# Create a record
class RecordForm(forms.ModelForm):
    class Meta:
        model = models.Record
        fields = ['Date', 'Category', 'description', 'type', 'Amount']
        widgets = {
            'Date': forms.DateInput(format=('%Y-%m-%d'), attrs={'type': 'date', 'class': 'form-control'}),
        }


def record_create(request, username):
    print("Record Create test username: ", username)
    if request.method == "POST":
        form = RecordForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            record.username = username
            record.save()
            return redirect(reverse("record_list_with_username", kwargs={'username': username}))
    else:
        form = RecordForm()
    return render(request, "system/record_form.html", {"form": form, "username": username})


def record_list(request, username):
    # 从数据库获取任务清单
    print("Current User username is: ", username)
    records = models.Record.objects.filter(username=username).order_by("Date")
    total_in = models.Record.objects.filter(username=username, type=models.Record_Type.In).aggregate(Sum('Amount'))
    total_out = models.Record.objects.filter(username=username, type=models.Record_Type.Out).aggregate(Sum('Amount'))
    total_in_amount = round(total_in['Amount__sum'] or 0, 2)
    total_out_amount = round(total_out['Amount__sum'] or 0, 2)
    total = round((total_in_amount - total_out_amount), 2)
    try:
        fund = Fund.objects.get(username=username)
        budget = fund.Budget
        rest = fund.Rest
    except Fund.DoesNotExist:
        # If there is no corresponding Fund record, set the default value
        budget = 0
        rest = 0
    print("total: " ,total)
    context = {
        "records": records,
        "total_in": total_in_amount,  # If there is no In record, 0 is displayed.
        "total_out": total_out_amount,
        "total": total,
        "budget": budget,
        "rest": rest,
        "username": username,
    }
    return render(request, "system/record_list.html", context)


# Retrieve a single record
def record_detail(request, pk, username):
    # Get the pk value of a single task from the url, and then query the database to get a single object
    record = get_object_or_404(Record, pk=pk)
    print("record: ", record)
    return render(request, "system/record_detail.html", {"record": record, "username": username, })


def record_update(request, pk, username):
    # Get the pk value of a single task from the url, and then query the database to obtain a single object instance
    record_obj = get_object_or_404(Record, pk=pk)
    if request.method == 'POST':
        form = RecordForm(instance=record_obj, data=request.POST)
        if form.is_valid():
            form.save()
        record_id = Record.id
        print("Record id: ", record_id)
        return redirect(reverse("record_detail", args=[ pk, username, ]))
    else:
        form = RecordForm(instance=record_obj)
    return render(request, "system/record_form.html", {"form": form, "object": record_obj, "username": username})


# Delete a single record
def record_delete(request, username, pk):
    record_obj = get_object_or_404(Record, pk=pk)
    record_obj.delete()  # 删除然后跳转
    return redirect(reverse("record_list_with_username", kwargs={'username': username}))


def set_budget(request):
    username = request.session.get('username')
    if request.method == 'POST':
        username = request.session.get('username')
        budget = Decimal(request.POST.get('Budget'))

        fund = Fund.objects.filter(username=username).first()
        total_in = Record.objects.filter(username=username, type=Record_Type.In).aggregate(Sum('Amount'))
        total_out = Record.objects.filter(username=username, type=Record_Type.Out).aggregate(Sum('Amount'))
        total_in_amount = round(total_in['Amount__sum'] or 0, 2)
        total_out_amount = round(total_out['Amount__sum'] or 0, 2)
        rest = round(budget + total_in_amount - total_out_amount, 2)

        if fund:

            # If present, only update the Budget field
            Fund.objects.filter(username=username).update(Budget=budget, Rest=rest)
        else:
            # If it does not exist, create a new Fund record

bookbalance/djangoProject/templates/system/account.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Account Setting</title>
{% endblock %}
{% block content %}
<main>
   <div class="content-area">
    <h3>Account Settings</h3>
    <table class="table table-bordered text-center">
        <thead>
        <tr>
            <th class="td">Username</th>
            <td class="td">Email/Phone Number</td>

        </tr>
        </thead>
        <tr>
             <th>{{ user.username }}</th>
             <td>{{ user.email }}</td>

         </tr>

    </table>

<br>
<br>

    <form method="post" class="text-center login_box">
        <!-- {% csrf_token %} -->
        <div class="form_text_ipt">Type your old password:
            <input name="old_password" type="text" placeholder="Old password" required="">
        </div>
        <br>
        <div class="form_text_ipt" >Type your new password:
            <input name="new_password" type="password" placeholder="New password" required="">
        </div>
        <br>
        <div class="form_text_ipt">Repeat your old password:
        <input name="repassword" type="password" placeholder="Repeat password" required="">
    </div>
    <br>

        <button type="submit" class="search-link2">Change Password</button>
        <a class="search-link2" href="{% url 'mainpage_with_username' username=username %}">Home Page</a>
    </form>



    {% if messages %}
    <ul class="messages text-center">
        {% for message in messages %}
            <li class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %} 


    </div>

</main>
{% endblock %}

bookbalance/djangoProject/templates/system/chatbox.html
{% extends "base.html" %}
{% block title %}
<title>ChatBox Page</title>
{% endblock %}

{% block content %}
<main class="chatbox-page">
    <br>
<h3 >Enter your query and get related reocrd.</h3><br>
<form action="{% url 'chatbox' %}" method="post">
    {% csrf_token %}
    <label for="user_query">Enter your query:</label>
    <input type="text" id="user_query" name="query">
    <label for="date">Date (YYYY-MM-DD):</label>
    <input type="text" id="date" name="date">
    <input type="submit" value="Submit">
</form>
    {% if record or records %}
    <h4 class="content-area text-center">Results</h4>
    <table class="table table-bordered content-area text-center" width="600">
        <tr>
            <th>Date</th>
            <th>Category</th>
            <th>Description</th>
            <th>Type</th>
            <th>Amount</th>
        </tr>
        {% if record %}
        <tr>
            <td>{{ record.Date }}</td>
            <td>{{ record.get_Category_display }}</td>
            <td>{{ record.description }}</td>
            <td>{{ record.get_type_display }}</td>
            <td>${{ record.Amount }}</td>
        </tr>
        {% endif %}
        {% if records %}
        {% for record in records %}
        <tr>
            <td>{{ record.Date }}</td>
            <td>{{ record.get_Category_display }}</td>
            <td>{{ record.description }}</td>
            <td>{{ record.get_type_display }}</td>
            <td>${{ record.Amount }}</td>
        </tr>
        {% endfor %}
    </table>
{% endif %}
    </table>
{% else %}
    <p>No records found.</p>
{% endif %}
</main>
{% endblock %}

bookbalance/djangoProject/templates/system/index.html
{% extends "base_login.html" %}
{% load static %}
{% block title %}
<title>Index</title>
{% endblock %}
{% block link %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
    rel="stylesheet">

    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>

{% endblock %}
{% block content %}
        <main>

        <h3>Book Balance Index Home</h3><br>
        <div>
            <p>
            <img src="{% static 'images/buget1.jpg' %}"
                alt="Picture Example of BookBalance Main Page" width="100%" height="40%" /></p>
        </div>
        <div>
            <p>
            <img src="{% static 'images/logo-uog.png' %}"
                alt="Picture Example of BookBalance Main Page" />BookBalance, Makes life better.</p>
        </div>
</main>

{% endblock %}

bookbalance/djangoProject/templates/system/log_in.html
{% extends "base_login.html" %}
{% load static %}
{% block title %}
<title>Log In</title>
{% endblock %}
{% block link %}
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-login.css' %}">

    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'js/base.js' %}"></script>

{% endblock %}
{% block content %}
	<main>
		<div class="content-area">
			<p>
			<div class="wrap login_wrap">
			<div class="content">
				<div class="login_box">
					<div class="login_form">
						<h3><div class="login_title">
							Log In
						</div></h3>
						<form action="{% url 'login' %}" method="post">

							<div class="form_text_ipt">
								<p>
                                <label>
                                    <input name="username" type="text" placeholder="username" required>
                                </label>
                            	</p>
                            </div>

							<div class="form_text_ipt">
								<p>
                                <label>
                                    <input name="password" type="password" placeholder="password" required>
                                </label>
                            	</p>
                            </div>

							<div class="form_check_ipt">
								<div class="left check_left">
									<input type="checkbox" name="remember" id="remember"> 
                                    <label for="remember">Save the password for next login.</label>
								</div>

							</div>
							<div class="form_btn">
								<button type="submit" > Log In </button>
							</div>
							<div class="form_reg_btn">
								<span>Still have no account?</span><a href="{% url 'register' %}">Register Now Here.</a>
							</div>
						</form>
                        {% if messages %}
                            <ul class="messages text-center">
                                {% for message in messages %}
                                    <li class="message {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
					</div>
				</div>
			</div>
		</div>
            </p>
		</div>
	</main>
{% endblock %}

bookbalance/djangoProject/templates/system/mainpage.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Main Page</title>
{% endblock %}
{% block content %}
<main>
   <div class="content-area">
   <h3>BookBalance: To balance your budget wisely</h3><br>
   <p>Welcome user {{ username }}!</p>
    <!-- <a href="{% url 'logout' %}">Logout</a> -->
    <p><a class="search-link2" href="{% url 'record_list_with_username' username=username %}">See current records here</a>
    

    <a class="search-link2" href="{% url 'account' username=username %}">Account Setting</a></p>
    </div>


    <div class="image-grid">
      <div class="image-item"><img src="{% static 'images/grocery.png' %}" alt="Image 1"><p>Grocery</p></div>
      <div class="image-item"><img src="{% static 'images/entertainment.png' %}" alt="Image 2"><p>Entertain</p></div>
      <div class="image-item"><img src="{% static 'images/transportation.png' %}" alt="Image 3"><p>Transport</p></div>
      <div class="image-item"><img src="{% static 'images/housing.png' %}" alt="Image 4"><p>Housing</p></div>
      <div class="image-item"><img src="{% static 'images/medical.png' %}" alt="Image 5"><p>Medical</p></div>
      <div class="image-item"><img src="{% static 'images/education.png' %}" alt="Image 6"><p>Education</p></div>
      <div class="image-item"><img src="{% static 'images/investment.png' %}" alt="Image 7"><p>Investment</p></div>
      <div class="image-item"><img src="{% static 'images/other.png' %}" alt="Image 8"><p>Other</p></div>
    </div>

    <br>
</main>
{% endblock %}

bookbalance/djangoProject/templates/system/record_detail.html
{% extends "base.html" %}
{% block title %}
<title>Current Record Detail</title>
{% endblock %}

{% block content %}
<main>
   <div class="content-area">
    <p>Hi {{ username }}</p>
 <p> Record Name: {{ record.id }} | <a href="{% url 'record_update' username=username pk=record.id %}">Update</a> |
     <a href="{% url 'record_delete' username=username pk=record.id %}">Delete</a>
 </p>
 <!-- <p> Record Status: {{ record.get_status_display }} </p> -->
 <p> Record Category: {{ record.get_Category_display }} </p>
  <p> Record Description: {{ record.description }} </p>
   <p> Record Date: {{ record.Date|date:"Y-m-d" }} </p>
    <p> Record Amount: {{ record.Amount }} </p>
 
 <p> <a href="{% url 'record_list_with_username' username=username %}">View All Records</a> |
     <a href="{% url 'record_create_with_username' username=username %}">New Record</a>
 </p>
</div>
</main>
{% endblock %}

bookbalance/djangoProject/templates/system/record_form.html
{% extends "base.html" %}
{% block title %}
<title>Record Form</title>
{% endblock %}

{% block content %}
<main>
   <div class="content-area">

 <h3>{% if object %}Edit Record {% else %} Create New Record {% endif %}</h3>

     <form action="" method="post" enctype="multipart/form-data" class="record-form">
         {% csrf_token %}
         <input type="hidden" name="username" value="{{ username }}">
         {{ form.as_p }}
         <p><input type="submit" value="Submit">
         <a href="{% url 'record_list_with_username' username=username %}" class="search-link2" value="Back">Back</a></p>
     </form>

 </div>
</main>
{% endblock %}

bookbalance/djangoProject/templates/system/record_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>Record List</title>
{% endblock %}

{% block content %}
<main>
   <div class="content-area text-center">

     <h3>Record List</h3>

    <div class="image-grid">
      <div class="image-item"><img src="{% static 'images/grocery.png' %}" alt="Image 1">Grocery</div>
      <div class="image-item"><img src="{% static 'images/entertainment.png' %}" alt="Image 2">Entertain</div>
      <div class="image-item"><img src="{% static 'images/transportation.png' %}" alt="Image 3">Transport</div>
      <div class="image-item"><img src="{% static 'images/housing.png' %}" alt="Image 4">Housing</div>
      <div class="image-item"><img src="{% static 'images/medical.png' %}" alt="Image 5">Medical</div>
      <div class="image-item"><img src="{% static 'images/education.png' %}" alt="Image 6">Education</div>
      <div class="image-item"><img src="{% static 'images/investment.png' %}" alt="Image 7">Investment</div>
      <div class="image-item"><img src="{% static 'images/other.png' %}" alt="Image 8">Other</div>
    </div>

    <br>
    
     <p><a class="search-link2" href="{% url 'record_create_with_username' username=username %}">+ Add A New Record</a>
     <a class="search-link2" href="{% url 'set_budget' %}">+ Set a budget</a></p>

     <h5>User {{ username }}'s Record List History:</h5>
     <br>
     
        <table class="table table-bordered" width="600">
        <thead>
        <tr>
            <th class="td">Time</th>
            <td class="td">Category</td>
            <td class="td">Description</td>
            <td class="td">Amount</td>
            <td class="td">In/Out</td>
            <td class="td">Edit/Delete</td>
        </tr>
        </thead>
     {% for record in records %}
         <tr>
             <th>{{ record.Date|date:"Y-m-d" }}</th>
             <td>{{ record.get_Category_display }}</td>
             <td>{{ record.description }}</td>
             <td>{{ record.Amount }}</td>
             <td>
                 {% if record.type == 1 %}
                     Out
                 {% else %}
                     In
                 {% endif %}
             </td>
             <td class="text-center">
                 <a class="link text-center" href="{% url 'record_update' username=username pk=record.id %}">Update</a> |
                 <a class="link text-center" href="{% url 'record_delete' username=username pk=record.id %}">  Delete</a>
             </td>
         </tr>
     {% endfor %}
        </table>
        <div class="row">
            <div class="col text-center">
                <p><strong>Budget:</strong> {{ budget|floatformat:2 }}</p>
            </div>
            <div class="col">
                <p><strong>Rest:</strong> {{ rest|floatformat:2 }}</p>
            </div>
            <div class="col">
                <p><strong>Total In:</strong> {{ total_in|floatformat:2 }}</p>
            </div>
            <div class="col">
                <p><strong>Total Out:</strong> {{ total_out|floatformat:2 }}</p>
            </div>
            <div class="col">
                <p><strong>Total:</strong> {{ total|floatformat:2 }}</p>
            </div>
        </div>
    {% if username %}
    
    
    <p><a class="search-link2" href="{% url 'mainpage_with_username' username=username %}">Home Page</a></p>
    {% endif %}

   </div>
</main>
{% endblock %}

bookbalance/djangoProject/templates/system/search.html
{% extends "base.html" %}

{% block content %}
<!-- search form -->
<form action="{% url 'search' %}" method="post" class="content-area text-center">
    {% csrf_token %}
    <label for="date">Choose a date:</label>
    <input type="date" id="date" name="date" required>
    <button class="search-link2" type="submit">Search</button>
</form>

<!-- search results -->
{% if records %}
    <h2 class="content-area text-center">Search Results</h2>
    <table class="table content-area text-center">
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Type</th>
            </tr>
        </thead>
        <tbody>
            {% for record in records %}
            <tr>
                <td>{{ record.Date|date:"Y-m-d" }}</td>
                <td>{{ record.get_Category_display }}</td>
                <td>{{ record.description }}</td>
                <td>{{ record.Amount }}</td>
                <td>{{ record.get_type_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p class="content-area text-center">Total In: {{ total_in }} |
    Total Out: {{ total_out }} |
    Net Total: {{ total }}</p>
{% else %}
<br>
    <p class="content-area text-center">No records found for the selected date.</p>
{% endif %}
{% endblock %}

bookbalance/djangoProject/templates/system/set_budget.html
{% extends "base.html" %}
{% block title %}
<title>Set Budget</title>
{% endblock %}
{% block content %}
<main>
   <div class="content-area">
		<div class="wrap login_wrap">
			<div class="content">

				<div class="logo"></div>

				<div class="login_box">

					<div class="login_form">
						<div class="login_title text-center">
							<h4>Set Budget</h4>
						</div>
						<form action="{% url 'set_budget'%}" method="post" class="record-form">
                            <div class="form_text_ipt">
								<input name="Budget" type="text" placeholder="Budget">
                            </div>
                            <div class="form_btn">
								<p>
									<input type="submit" value="Submit">
									<a href="{% url 'record_list_with_username' username=username %}" class="search-link2" value="Back">Back</a>
								</p>
							</div>
						</form>

						</div>
					</div>
				</div>
			</div>
		</div>


    
</main>
{% endblock %}

bookbalance/djangoProject/templates/system/support.html
{% extends "base.html" %}
{% block title %}
<title>Support Page</title>
{% endblock %}
{% block content %}

    <main>
        <div class="content-area">
            <h3>Support</h3>
            <p>Need help or have questions? Contact us through the form below or reach out via email at support@example.com.</p>
            <form id="support-form" action="{% url 'report'%}" method="post">
                

                <label for="email">Your Email</label>
                <input type="email" id="email" name="email" required>

                <label for="message">Your Message</label>
                <textarea id="message" name="message" rows="4" required></textarea>

                <button type="submit">Send Message</button>
            </form>
        </div>
    </main>

{% endblock %}